# from ubuntu 20.04
FROM ubuntu:focal

# dependencies
RUN apt-get -y update
RUN apt-get -y install curl git python3 python3-pip python3-dev python3-venv

# install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
