name: Build Docker Container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-focal

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: etc/Dockerfile
          tags: g29-py:latest
